from datetime import datetime
current_time=datetime.now()
print(current_time)
Format1=current_time.strftime("%Y-%m-%d %H:%M:%S")
print(Format1)
Format2=current_time.strftime("%m/%d/%Y")
print(Format2)
Format3=current_time.strftime("%d,%m %d,%Y")
Format4=current_time.strftime("%d-%m-%d,%Y %H:%M:%S %p")
print(Format4)
Format5=current_time.strftime("%d-%m,%d %H:%M:%S %Z %Y")
print(Format5)
Format6=current_time.isoformat()
print(Format6)
Format7=current_time.strftime("%d")
print(Format7)
Format8=curent_time.strftime("%H:%M:%S")